name: Hello World Workflow
on: [push]
jobs:
  build:
    name: Hello world job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Action to check out repository code
    - name: Print a message
      run: echo "Hello, GitHub Actions!"